services:
  backend:
    build:
      context: .
      dockerfile: ./docker/local/python/Dockerfile
    container_name: backend
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/usr/src
