name: ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Formatter by autopep8
      run: autopep8 --diff --recursive .
    - name: Formatter by Black Formatter
      run: black --diff .
    - name: Linter by Pylint
      run: pylint ./
    - name: Linter by Flake8
      run: flake8
    - name: Linter by Mypy
      run: mypy ./
